### ISSUE TITLE
Feature request: Bisecting SortedListWithKey directly with a key.

### ISSUE THREAD

**Issue by percontation** [grantjenks/sorted_containers#20]
I'd like to operate on a SortedListWithKey by passing it keys directly, instead of passing values that it runs through `self._key(val)`.

In other words, I'd like a class of `*_key ` methods that work like: `assert SortedListWithKey(['a','b','c'], lambda x: x.upper()).bisect_left_key('B') == 1`.

While this sounds suspiciously like a SortedDict, in my use case it'd be super handy to have a drop-in replacement for a list.

I'd have send this as a PR, but I'd feel bad adding a dozen `*_key` variant methods. Maybe something cute like a `.viewdict()` method would be a Pythonic alternative? As long as the "DictView" retained the bisect methods, anyways; those are the ones I care about for my use case ;)

**Comment by grantjenks** [comment]
Sorry for the delay. Added and deployed in v0.9.5 now on PyPI.
