### ISSUE TITLE
Feature Request: Ability to have popitem remove the smallest item from a SortedDict

### ISSUE THREAD

**Issue by smmalis37** [grantjenks/sorted_containers#22]
As the title says, it would be nice to have some sort of flag in popitem that would determine whether the largest item is removed or the smallest item is.

**Comment by grantjenks** [comment]
I think that's reasonable. It would also help close the gap in the api with blist.sorteddict.

As a temporary work-around you can use:
```
def popitem_smallest():
    key = sorted_dict.iloc[0]
    value = sorted_dict[key]
    del sorted_dict.iloc[0]
    return key, value
```

**Comment by grantjenks** [comment]
Added at f567d59
