### ISSUE TITLE
Add tags for versions

### ISSUE THREAD

**Issue by vinnyrose** [grantjenks/sorted_containers#23]
It would be very helpful if this repo had tagged version. Here are the commands for all of the versions.

    git tag -a v0.5.0 3573f5e537 -m ''
    git tag -a v0.6.0 6b3abdbc44 -m ''
    git tag -a v0.7.0 10ea09080b -m ''
    git tag -a v0.8.0 54ff94dbe3 -m ''
    git tag -a v0.8.1 dcba212cd1 -m ''
    git tag -a v0.8.2 247b960b09 -m ''
    git tag -a v0.8.3 490496aa40 -m ''
    git tag -a v0.8.4 da82b75926 -m ''
    git tag -a v0.8.5 f51423bae6 -m ''
    git tag -a v0.9.0 bbce755011 -m ''
    git tag -a v0.9.1 66c39a18bb -m ''
    git tag -a v0.9.2 f7a0ab70fa -m ''
    git tag -a v0.9.3 895b7490b4 -m ''
    git tag -a v0.9.4 001038743f -m ''
    git push --tags

**Comment by grantjenks** [comment]
Good idea. Will do soon.

**Comment by grantjenks** [comment]
Pushed. Sorry for the delay.
