### ISSUE TITLE
Clarify Key-func Arg to SortedDict (docs issue)

### ISSUE THREAD

**Issue by tallforasmurf** [grantjenks/sorted_containers#24]
In the doc (http://grantjenks.com/docs/sortedcontainers/sorteddict.html) one paragraph documents the optional key argument, but the word "key" is used many times for other purposes, and there is no example use of using a key-func.

For clarity I recommend using *key_function* for this argument not simply *key*; and including an example. One real-life example would be using a key-func generated by the natsort package to do locale-aware sequencing of the dict but you no doubt can think of others.

**Comment by grantjenks** [comment]
Good point. I'll update the docs to use *key_function* and add an example in the introduction that uses natural sort or some other.

**Comment by grantjenks** [comment]
Note that this argument is not a keyword argument, it's positional. Though it has the name `key`, that is only to remind readers of the similar `key` callable that can be passed to `sorted`.

I think it's worth adding an example in the introduction. I'll work on that.

**Comment by grantjenks** [comment]
Fixed at 6085224
