### ISSUE TITLE
Why SortedListWithKey?

### ISSUE THREAD

**Issue by nbecker** [grantjenks/sorted_containers#28]
I want a sorted list with a user-specified key, but why is this a different object, rather than an option on the constructor for SortedList?

**Comment by grantjenks** [comment]
There's a few reasons:

1. The first is historical. It wasn't needed at first. Only SortedList existed and it had no key parameter and that was good-enough. For a while I got by making things into tuples and using boxing/unboxing functions. But eventually I saw the power of a key function and I wanted that too.
2. SortedListWithKey uses different internal data structures, mainly the `_keys` array. And this changes how most methods operate. There are a handful that are the same between the two: `_pos`, `_loc`, and those that only concern indexing.
3. Supporting keys makes the performance generally slower. It's documented in the performance comparison and it's not terribly large but it's there.
4. Supporting keys takes more memory. Even if the key is already part of the value stored, we've got to store at least a pointer to that part in a list.

So where possible, I try to use a SortedList but I too enjoy the utility of the key-function when needed.

I've wanted to unify the API for a while but I've not known the best way to do so. Most recently my thoughts were too:

1. Move SortedListWithKey to sortedlist.py and make it inherit from SortedList.
2. Remove the identical methods for indexing from SortedListWithKey.
3. Add a `__new__` method to SortedList which accepts a `key` keyword argument. When this argument is observed, constructing a SortedList will actually result in a SortedListWithKey which will be a subclass.

Your thoughts? Do you have a particular use case where this is bothersome?

**Comment by grantjenks** [comment]
Changed at 1b7810. In the next release, calling SortedList(..., key=..., ) will return an instance of subtype SortedListWithKey.

**Comment by grantjenks** [comment]
Deployed to PyPI in version 1.4.2
