### ISSUE TITLE
please include docs and tests in the PyPI tarball

### ISSUE THREAD

**Issue by sandrotosi** [grantjenks/sorted_containers#29]
HEllo,
I'm preparing the Debian package for sortedcontainers, and it would be really cool if in the next releases you could include docs and tests in the tarball released on PyPI so that the packaging could build&ship the documentation and we can run unittest at package build time

Thanks for considering,
Sandro

**Comment by grantjenks** [comment]
Hi Sandro, I'm open to that but tell me more about your use case. SortedContainers is pure-Python so there's no need to distribute built binaries. A simple `pip-python install sortedcontainers` should be all you need. Is there a separate benefit to Debian packages that I'm unaware of?

I've considered including the tests actually at sortedcontainers.tests but nothing has particularly motivated me.

Also, all the documentation including the images from the performance comparison are 22MB which is pretty large for a PyPI release that only really needs four python files.

Right now you can get everything you want by downloading a zipball tagged at the desired release. Something like: https://github.com/grantjenks/sorted_containers/zipball/v0.9.6 Does that help you?

**Comment by grantjenks** [comment]
For reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790504

@sandrotosi Can you share the tool you use for making Debian packages from PyPI?

**Comment by sandrotosi** [comment]
hi @grantjenks sorry for the late reply.

Please keep in mind that not everyone is fine with using pip to install python modules, in particular for large systems installation. At Debian we decided to ship binary packages, and that is the preferred way to add software to the distribution (and what I did, creating a debian pkg for sorted containers).

The test could also not necessarily exposed as a submodule, but as long they are available in the tarball, anyone can use them to verify the installation is fine (and they ofter reveal surprising bugs on some of the Debian weird architectures).

I understand your concern about the size of the tarball (even though size, diskspace and network speed are kinda cheap these days), the reason I prefer to use PyPI is that's what most users use and what you released as a software to use, while git tags ofter contains files which are not release in PyPI (for whatever reason, like travis.yml for example), but I might indeed consider using the tag indeed.

As for the tool, 'vi' is a good enough answer? :) what I did is grabbing the tarball, created a packaging skel with dh_make and then edit the files by hand. No tools.

**Comment by grantjenks** [comment]
@sandrotosi Thanks for the reply. I'm unaccustomed to the _Debian way_ but glad to support it to encourage adoption. I'm currently a CentOS-er but often tempted by what I hear is an easier update process.

I think using the tag to fetch the github zipball is the best solution. Note that, for the tests, you'll need Debian's `python-nose` package. Also, if you want `python setup.py test` to work out-of-the-box then you'll need Debian's `python-tox` package. I believe that's all the dependencies for building the docs and running the tests.

I understand your waiting now for review. Is that correct? Does that usually take days, weeks, months?

Let me know how I can help. Thanks for your contribution.

**Comment by sandrotosi** [comment]
@grantjenks the review takes an unknown amount of time :) it is up to a small group of people to check that the package can actually be part of debian (it has a valid license allowing redistribution etc etc), recently it has been quite a quick process taking some days to few weeks. Once approved I'll have a look at move the package to use the github tags (only if you promise never to retag a release! :D )

**Comment by grantjenks** [comment]
Looks like it was accepted to Debian "sid" and Ubuntu "wily":

* https://packages.debian.org/sid/python/python-sortedcontainers
* http://packages.ubuntu.com/wily/python-sortedcontainers

Let me know if you need anything more from me.
