### ISSUE TITLE
SortedSet difference doesn't preserve original order

### ISSUE THREAD

**Issue by beaumartinez** [grantjenks/sorted_containers#32]
Hi,

I'm really enjoying using `sorted_containers` so far. However I've noticed when calculating the difference between two `SortedSet`s, I don't get the result I expect.

As a bit of a contrived example, imagine the following—

    In [44]: SortedSet(['b', 'd', 'c', 'e', 'a']) - SortedSet(['e', 'b'])
    Out[44]: SortedSet(['a', 'c', 'd'], key=None, load=1000)

I expected the original order in the original set to have been preserved for the items, relative to each other. Ie, I expected—

    Out[44]: SortedSet(['d', 'c', 'a'], key=None, load=1000)

Since that's how I defined the elements in the first place. It looks like it's been ordered alphabetically automatically (not what I wanted).

My use case is: I'm trying to find new URLs using two different sets, preserving the order they were added. I figured SortedSet would do this for me (in the same was as Python's normal `OrderedDict` preserves order of items as you add them).

Is this expected behaviour, or is this something we could improve? I noticed the code (as currently defined) is—

    def difference(self, *iterables):
        """
        Return a new set with elements in the set that are not in the
        *iterables*.
        """
        diff = self._set.difference(*iterables)
        new_set = self.__class__(key=self._key, load=self._load, _set=diff)
        return new_set

([Permalink.](https://github.com/grantjenks/sorted_containers/blob/71480ca0dfe30ddf165cb2a9a225ffe9b9744d7a/sortedcontainers/sortedset.py#L186))

So maybe using Python's regular `set` type is what's causing this.

Thanks.

**Comment by grantjenks** [comment]
`SortedSet` is not an `OrderedSet`. The values are maintained in `sorted` order not insertion order.
