### ISSUE TITLE
Bug or gotcha? __iter__ not remove-safe

### ISSUE THREAD

**Issue by ptype** [grantjenks/sorted_containers#36]
>>> from sortedcontainers import SortedSet
>>> s = SortedSet([1,2,3,4,5,6])
>>> s
>>> SortedSet([1, 2, 3, 4, 5, 6], key=None, load=1000)

>>> for i in s:
>>>     s.remove(i)
...
...
>>> s
>>> SortedSet([2, 4, 6], key=None, load=1000)

**Comment by ptype** [comment]
Compare with native set:

>>> S={1,2,3,4,5,6}
>>> for i in S:
...  S.remove(i)
...
... Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Set changed size during iteration

**Comment by grantjenks** [comment]
Sorry, that's a gotcha.

If you need to remove all the elements, you can use `SortedSet.clear`

If you need to edit and iterate, use indexing. Something like:

```python
pos = 0
values = SortedSet(range(100))

while pos < len(values):
    value = values[pos]
    if prime(value):
        del values[pos]
    else:
        pos += 1
```

Or, even better, use set operations:

```python
def test(value):
    return True # Logic goes here

values = SortedSet(range(100))

# Remove all values where `test` returns True
values.difference_update(value for value in values if test(value))
```

**Comment by grantjenks** [comment]
Docs updated at 54606e8
