### ISSUE TITLE
Force refresh?

### ISSUE THREAD

**Issue by matinca** [grantjenks/sorted_containers#39]
Is there a way to force refreshing, eg. when using SortedListWithKey and a value of an element that influences the key is changed? Example:

`>>>a = SortedListWithKey(key=lambda x: x[1])`
`>>>a.add([0, 3])`
`>>>a.add( [0, 2])`
`>>>a`
`SortedListWithKey([[0, 2], [0, 3]], key ...`
`>>>a[0][1] = 5`
`>>>a`
`SortedListWithKey([[0, 5], [0, 3]], key ...`

**Comment by grantjenks** [comment]
Not in the current api. I've wondered about this functionality before though. There aren't many internals for the underlying implementation to use to speed this up.

Once you get things out-of-sync like this, some of the algorithms will stop working. You're better off doing:

```
temp = a.pop(index)
temp[1] = 5
a.add(temp)
```

**Comment by matinca** [comment]
Ok. Thanks!
