### ISSUE TITLE
Add sortedarray

### ISSUE THREAD

**Issue by pombredanne** [grantjenks/sorted_containers#42]
It would be awesome to have a sortedarray type. The benefit of array is a more compact size for a known type, such as  smaller ints.

**Comment by grantjenks** [comment]
Interesting idea. Would it have the same interface as SortedList? Does it need key function support?

If you simply need integers to take less space, consider using PyPy. Their implementation uses tagged pointers so most integers take only 8 bytes. Because SortedContainers is pure-Python it really screams on PyPy.

**Comment by pombredanne** [comment]
> Would it have the same interface as SortedList? 

Yes

> Does it need key function support?

No. I am interested only in integers. ;) and I think a key would not make sense for `arrays`: since they are typed, the sort order is IMHO implied by the type.

> If you simply need integers to take less space, consider using PyPy.

Well, I cannot really decide which Python runtime a user may use with my wares. And since some of it still has dependencies on a few C extensions, Pypy is not really an option (yet).  And for a 32 bit int, 2 bytes beats 8 bytes by a small margin which ever way you look at it.

Now, what I am really looking is a screaming and compact sorted integer set, ideally in pure Python. Frozen is fine, mutability is not a big deal: lookup, iteration, union and intersection are the main operations.  
I have been using plain `frozenset` subclasses with a backing sorted list, sparse sorted `lists` then `arrays` where the index is the value (similar to a bitmap) and bitmaps as well (again where the index is the value and a bit set to one means the value exists in the set)  (using [bitarray](https://pypi.io/project/bitarray/) and more recently playing with [inbitset](https://pypi.io/project/intbitset/) ) . Ideally something like a [roaring bitmap](http://roaringbitmap.org/) which interestingly shares some attributes with your sortedcontainers in terms of nested list structure. There is a Python roaring implementation in whoosh but I did not evaluate it yet.

**Comment by grantjenks** [comment]
SortedContainers doesn't quite fit this use case.

The best solution will depend a lot on your data. What range of integers? How dense/sparse? What do your performance measurements show?

For dense integers with a narrow range, a bitmap is a good choice. I would look at numpy which supports elementwise bitwise operations: http://docs.scipy.org/doc/numpy/reference/routines.bitwise.html
