### ISSUE TITLE
Implement a new function

### ISSUE THREAD

**Issue by thestick613** [grantjenks/sorted_containers#44]
Implement a function in SortedList which removes all items that are greater or lower than a value. This could be useful in a moving window counter.

**Comment by grantjenks** [comment]
Interesting. How do you currently do it?

**Comment by thestick613** [comment]
There are many use cases for such a thing - you could do rate limiting or you could show the most popular x actions in the last 5 minutes, etc. Most people use redis sorted sets, but it's a little overkill for me.

I currently use https://limits.readthedocs.io/en/stable/ for rate limiting.

**Comment by grantjenks** [comment]
I agree there are a lot of use cases. Sorry, I was more interested in how you use the current API to solve this problem.

For example, you could do this to delete all values greater than 3.5 in a sorted list:

```python
In [1]: import sortedcontainers as soco

In [2]: sorted_list = soco.SortedList(range(10))

In [3]: index = sorted_list.bisect(3.5)

In [4]: del sorted_list[index:]

In [5]: sorted_list
Out[5]: SortedList([0, 1, 2, 3], load=1000)
```

I think numerical indexing and support for slicing would work for your use cases. Those are already implemented.

**Comment by thestick613** [comment]
`In [4]: del sorted_list[index:]` - I didn't know you could do that in `SortedList`. It's easy to do this now, thanks!
