### ISSUE TITLE
Maintain changelog?

### ISSUE THREAD

**Issue by Daenyth** [grantjenks/sorted_containers#46]
I noticed that the version in my requirements.txt is out of date vs what the latest is, but I can't find any changelog, release notes, or history file listing what's changed in the library. Without that, I need to do a lot more manual verification to upgrade.

**Comment by grantjenks** [comment]
I've meant to do that but generally get by with git. All the version changes are tagged in the history. Try simply doing:

    git log --oneline

And you'll see the changes alongside the version bumps.

Most changes are bug fixes, performance improvements, or added functionality. I can't think of any breaking changes that would harm your upgrade.

**Comment by grantjenks** [comment]
Done: http://www.grantjenks.com/docs/sortedcontainers/history.html
