### ISSUE TITLE
Add SortedDict.insert() Method => Setitem and Return Index

### ISSUE THREAD

**Issue by socketpair** [grantjenks/sorted_containers#49]
This function should optimally do the folllowing:

``` python
class SortedDict:
    def insert(self, key, value):
        self[key] = value
        return self.index(key)
```

Also, it may be useful to add such function to other structures, like `SortedSet` (in th case, SortedSet should return inserted index instead of `None`).

In order not to clash with existing `.insert()` it may be desirable to name that new function `put()` for all types of containers

**Comment by grantjenks** [comment]
What do you use that for?

**Comment by grantjenks** [comment]
Previous request for something similar: https://github.com/grantjenks/sorted_containers/issues/6

**Comment by socketpair** [comment]
I am excited! That issue is exactly what I ask!

Usecase is follow:
Insert into conatiner and examine all items after/before imserted item.

Also, it will be nice to have items() iterator for SortedDict that starts with specific index.

**Comment by grantjenks** [comment]
Does the workaround provide suffice then? The referenced issue suggested subclassing and modifying the behavior to your needs.

For an items() iterator that starts with a specific index you have two choices:

1. ItemsView.__getitem__ supports slicing.
2. SortedDict.islice returns an iterator over keys of a slice. For each key, simply lookup the value.

Code examples:

```
In [1]: from sortedcontainers import SortedDict

In [2]: data = SortedDict(enumerate('abcde'))

In [3]: data.items()
Out[3]: [(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd'), (4, 'e')]

In [4]: data.viewitems()[2:4]
Out[4]: [(2, 'c'), (3, 'd')]

In [5]: [(key, data[key]) for key in data.islice(2, 4)]
Out[5]: [(2, 'c'), (3, 'd')]
```

**Comment by grantjenks** [comment]
In v2, the SortedDict.items() returns a view which supports indexing.

v2 is coming soon (in May, 2018)
