### ISSUE TITLE
Use autodoc for API documentation

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/sorted_containers#50]
Use Sphinx's autodoc module for API documenation.

Also change:
- "iff" to "if and only if"
- Make sure parameters match docstrings.

**Comment by socketpair** [comment]
Also SortedDict doc has bug in `bisect**` functions. For example:

```
d.bisect_left(key):
...
If key is already present in SortedDict, the insertion point will be before (to the left of) any existing entries.
```

But Sorted dict may have only one entry with given key. So it's not possible to have item at left or at right position next to existing item. Seems, all bisect functions should return index of item if key is present in this dict.

**Comment by grantjenks** [comment]
The bisect_left and bisect_right methods do not have the same behavior for SortedDict:

```
In [1]: from sortedcontainers import SortedDict

In [2]: data = SortedDict(enumerate('abcde'))

In [3]: data.bisect_left(2)
Out[3]: 2

In [4]: data.bisect_right(2)
Out[4]: 3

In [5]: data.bisect_left(2.5)
Out[5]: 3

In [6]: data.bisect_right(2.5)
Out[6]: 3
```

**Comment by grantjenks** [comment]
Done for v2, coming soon.
