### ISSUE TITLE
Add SortedDict.append Method

### ISSUE THREAD

**Issue by borisdan** [grantjenks/sorted_containers#54]
The SortedList class has an append method, which raises a _ValueError_ if the order has been violated. This allows much quicker creation of big SortedList, given that the initial input was sorted.
The same functionality can benefit vastly the creation of a big SortedDict, where the original input keys are sorted.

**Comment by grantjenks** [comment]
Some timings:

```
In [3]: %timeit SortedDict(items)
10 loops, best of 3: 73.1 ms per loop

In [4]: %%timeit
   ...: result = SortedDict()
   ...: for key, value in items:
   ...:     result[key] = value
   ...: 
1 loop, best of 3: 1.54 s per loop

In [5]: %%timeit
   ...: result = SortedDict()
   ...: dict_setitem = result._setitem
   ...: list_append = result._list.append
   ...: for key, value in items:
   ...:     dict_setitem(key, value)
   ...:     list_append(key)
   ...: 
1 loop, best of 3: 885 ms per loop
```

(3) is the recommended way to create a big SortedDict whether the input items are sorted or not. Initializing a SortedDict is heavily optimized in C-routines. Is there a reason this doesn't work in your case?

(4) is what I think you're currently doing. It's about twenty times slower than (3).

(5) is what I think you're proposing. This is still a bit simplified. There needs to be some kind of check for whether the key is already in the sorted dictionary. Notice that (5) is about twice as fast as (4). That's a big speedup but it's nothing like the performance of (3)

Can you pass the items to the SortedDict initializer? How do you know that it's safe to append?

Here's a prototype that extends SortedDict:

```
In [6]: class SortedDictWithAppend(SortedDict):
   ...:     def __init__(self, *args, **kwargs):
   ...:         super(SortedDictWithAppend, self).__init__(*args, **kwargs)
   ...:         self._list_append = self._list.append
   ...:     def append(self, key, value):
   ...:         if key not in self:
   ...:             self._list_append(key)
   ...:         self._setitem(key, value)
```

And timing that:

```
In [11]: %%timeit
   ....: result = SortedDictWithAppend()
   ....: for key, value in items:
   ....:     result.append(key, value)
   ....: 
1 loop, best of 3: 1.15 s per loop
```

If our base is 1.54s and our prototype is 1.15s then we could realize a 25% speedup. I'm on the fence about the utility of this. Could you share more about your use case? Is the prototype good enough?

**Comment by borisdan** [comment]
Here is the code bit (slightly edited, so I hope there are not 'bugs' I inserted):
The latter (after the blank line) is the meaningful part.

```
additional_indexes = sorted(additional_source_indexes.values())
from itertools import combinations
sources_combinations = [combination for i in xrange(0, len(additional_indexes) + 1) for combination in combinations(additional_indexes, i)]
possible_combos = {combo: combo for combo in sources_combinations}

additional_sources_hashes = SortedDict()
for src_filename in args.additional_sources:
    with open(src_filename) as f:
        for line in f:
            sources = additional_sources_hashes.get(h, tuple())
            mutable_sources = list(sources)
            mutable_sources.append(additional_source_indexes[src_filename])
            additional_sources_hashes[h] = possible_combos[tuple(mutable_sources)]
```

I am analyzing password hashes from big public leaks (LinkedIn, etc.).
My input are files of tens to hundreds of millions of hashes (normally 20 bytes). I want to mark per hash, in which sources it appears. Each hash can appear in any possible combination of the sources, including none or all.
Hundreds of millions of hashes quickly scale up to a heavy consumption of memory. Many hashes are repeated, so I don't want to hold them in memory more than once. Even if the Python runtime will avoid reallocating some identical strings, there is still lots of overhead due to the meta-data of the list. What happens in fact is that my Python eats up ~20GB of memory in this format, and loses lots of CPU time to kernel. 
Anyway - I can't pass the items ready for the initializer, because that would increase my memory consumption per each source file.
On the other hand - it is relatively easy and quick for me to create an input file that is sorted (GNU sort), and then append to the dict in order. 

On a side note, I actually tried switching to trie data structure, but the hit on the search performance is currently too much for me.

**Comment by grantjenks** [comment]
I don't see where `h` comes from in your code snippet. I also don't see where you are using the _sorted_ features of SortedDict. Maybe you could use a regular `dict` and then convert the result. For problems that exceed memory limits, I usually reach for SQLite. The lookups will be slower however. Maybe you could parallelize processing somehow.

I'm not sure how useful `SortedDict.append` will be for others. So I'm going to leave this open for voting. I think the use case is uncommon enough that using the `SortedDictWithAppend` snippet above is sufficient. But let's see if others want this feature.

**Comment by borisdan** [comment]
Sorry, as I said, that was just an edited excerpt from the code, so I made some mistake. _h_ is the hash, parsed from the file line.
The latter use is going over millions of hashes, and checking what additional sources they appear in. In other words, many many executions of _"h in additional_sources_hashes"_.

Anyway, I appreciate your openness, and hope other people fill find that useful too.

**Comment by grantjenks** [comment]
Closing for now. SortedList.append is removed in v2 (raises NotImplementedError). V2 to be deployed in May, 2018.
