### ISSUE TITLE
extending with an empty list causes exception

### ISSUE THREAD

**Issue by agroce** [grantjenks/sorted_containers#55]
Random testing with TSTL (https://github.com/agroce/tstl/blob/master/examples/sortedcontainers/sortedcontainers.tstl) shows that extending with an empty list causes an exception.  Normal Python list handles this fine, so seems like incorrect behavior:

>>> from sortedcontainers import SortedList
>>> l = SortedList()
>>> l.add('a')
>>> l2 = SortedList()
>>> l.extend(l2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/sortedcontainers/sortedlist.py", line 1083, in extend
    if values[0] < _lists[-1][-1]:
IndexError: list index out of range

**Comment by grantjenks** [comment]
That's a bug. Thanks for reporting. I'll fix it on Monday.

**Comment by grantjenks** [comment]
Fix deployed at v1.5.5
