### ISSUE TITLE
Merge sortedcollections

### ISSUE THREAD

**Issue by mrocklin** [grantjenks/sorted_containers#56]
I'm curious about the [sortedcollections](https://github.com/grantjenks/sortedcollections) spinoff library.  Why is it separate?  Are those recipes held to the same standards as the contents of `sorted_containers`?

**Comment by grantjenks** [comment]
Part of it is history. I prefer the name but didn't think of it when I started.

Another part is quality. Those recipes have coverage testing but not much stress testing. They also lack benchmarks and a discussion of alternatives.

Several of those recipes came from issues and I wanted a place to publish and publicize the solutions from those threads.

The last part is I wanted to demonstrate the utility of sorted containers. By implementing sorted list, dict, and set types, I wanted to show what other types could be created from those. The two I'm fond of are ValueSortedDict and IndexableSet.

**Comment by mrocklin** [comment]
I'm finding that `ValueSortedDict` solves my problem perfectly https://github.com/dask/distributed/issues/719#issuecomment-264968801

I asked the question mostly in order to avoid the maintenance overhead of extra packages: https://github.com/conda-forge/sortedcontainers-feedstock/issues/2

**Comment by mrocklin** [comment]
But, the reasoning sounds sensible to me.  Closing.
