### ISSUE TITLE
Infinite loop on slice assignment from self in SortedList

### ISSUE THREAD

**Issue by agroce** [grantjenks/sorted_containers#60]
Another random testing generated problem.  Works with Python list.  The exact slice parameters or list contents aren't particularly important.

from sortedcontainers import SortedList

list0 = SortedList()
list0.append('A')
list0 [1:1] = list0

**Comment by agroce** [comment]
List contents do technically matter in that if the sort order would be violated, you just get a ValueError.  You have to construct a case where self-insertion leads to valid sort, such as a list with one element, or a list of identical elements.

**Comment by grantjenks** [comment]
Yep, I see that. I will push out a fix today.

**Comment by grantjenks** [comment]
Fixed. Deployed at 1.5.6
