### ISSUE TITLE
SortedDict: Consider sorting by key and value

### ISSUE THREAD

**Issue by orbisvicis** [grantjenks/sorted_containers#63]
Its apparent you've put a lot of though into the API, so tell me what you think about this:

I propose sorting by value as well as key. There is no precedence in the standard library that `key` argument applies only to dictionary keys. The `sorted` builtin applies the `key` function to the entire entry - which just happens not to be a mapping.

Use case:

I have a bijective mapping, `str` -> `object`, `object` -> `str`, via two dictionaries. Sorting on `object` is meaningless, so I would like to mirror the `(str, id(object))` sorting. Since the `key` function can't access the value, I must maintain a third (regular) dictionary for the key function to access the key's value.

**Comment by grantjenks** [comment]
The SortedCollections package provides this functionality in ItemSortedDict: http://www.grantjenks.com/docs/sortedcollections/ SortedCollections is based on SortedContainers. I gather various recipes there.
