### ISSUE TITLE
Document total ordering requirement

### ISSUE THREAD

**Issue by tomas-teijeiro** [grantjenks/sorted_containers#64]
The following code gives an exception in version 1.5.7:

```python
import sortedcontainers

class Simple(object):
    def __init__(self):
        self.code = 0
        self.time = 0

    def __lt__(self, other):
        return self.time < other.time

o1 = Simple()
o1.time = 3
o1.code = 12
o2 = Simple()
o2.time = 3
o2.code = 18

l = sortedcontainers.SortedList()
l.add(o1)
l.add(o2)
print(l[1] in l) #This prints "False"
l.index(l[1])
```
`ValueError: <__main__.Simple object at 0x7f863f4c4a10> is not in list`

The problem seems to be related with the definition of the `__lt__` method, as in this case o1 ≮ o2, o2 ≮ o1, but o1 ≠ o2. From the [docs](http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html#sortedcontainers.SortedList.L.index), the `index()` function "Return the smallest k such that L[k] == x and i <= k < j", but that is not true in this case.

**Comment by grantjenks** [comment]
The next line of the docs explains:

    Raises ValueError if value is not present.

The behavior matches that of "list.index" in the standard library.

**Comment by tomas-teijeiro** [comment]
Of course the value is present, `l[1] in l` must always return `True`, by definition.

**Comment by grantjenks** [comment]
I'm not sure why "in" works but it's a fluke. You're notion of equality relies on the object's id but ordering relies on time. That's going to have undefined behavior. Best to define dunder eq and then it will be more clear.

You could also use a sorted list with key function that looks up the "time" field for ordering comparisons. That would work.

**Comment by tomas-teijeiro** [comment]
I know there are workarounds, but even so the bug is still present. You should not raise a `ValueError` if the object is indeed in the list. The example is just a minimum fragment of code to reproduce the error, but in the actual use case where I discovered this problem it is needed a class that overrides the '<' operator, but the equality must remain to be the identity. Other libraries like [blist](http://stutzbachenterprises.com/blist/) do not have this issue.

**Comment by grantjenks** [comment]
I have made a couple small changes to your snippet (added dunder repr method, renamed variables, and added optional blist import):

```python
from sortedcontainers import SortedList
# from blist import sortedlist as SortedList

class Simple(object):
    def __init__(self, time):
        self.time = time

    def __lt__(self, other):
        return self.time < other.time

    def __repr__(self):
        return '<Simple object with id: %s>' % id(self)

j = Simple(3)
k = Simple(3)

m = SortedList()
m.add(j)
m.add(k)
print(m[1] in m)
m.index(m[1])
```

Note that ``m[1] in m`` returns and displays ``False``. This unexpected result is due to the partial ordering you've defined. So the exception raised by "index" is no surprise. The SortedContainers methods do not contradict each other. The contains check returns false because you've stored objects with interchangeable order which are not equal in the sorted list. Consider these relationships:

```
In [32]: j < k
Out[32]: False

In [33]: k < j
Out[33]: False

In [34]: j == k
Out[34]: False
```

If "j" is neither less than nor greater than "k" then we would expect them equal. But that is not true in your case and so the algorithms behind the sorted list break down.

The surprise to me is that "blist" does work. But that's a fluke as well. Here's the relevant code from blist. I have annotated the lines with results from the debugger for evaluating ``m.index(k)``:

```python
    def index(self, value):  # _, k
        """L.index(value) -> integer -- return first index of value.
        Raises ValueError if the value is not present.
        """
        try:
            i, v = self._bisect_left(value)  # 0, j
        except TypeError:  # not reached
            raise ValueError
        i = self._advance(i, value)  # 1
        if i >= 0:  # 1 >= 0
            return i  # 1
        raise ValueError  # not reached

    def _advance(self, i, value):  # 0, k
        "Do a linear search through all items with the same key"
        key = self._u2key(value)  # k
        while i < len(self._blist):  # 0 < 2; 1 < 2
            if self._i2u(self._blist[i]) == value:  # j == k; k == k
                return i  # not reached; 1
            elif key < self._i2key(self._blist[i]):  # k < j
                break  # not reached; not reached
            i += 1  # 2
        return -1
```

Now when ``m.index(k)`` is evaluated, the "while" loop in "_advance" executes twice because "k < j" evaluates as "False" and does not break out of the loop. That's a fluke due to the partial ordering.

The best ways to support ``Simple`` objects are to define a total ordering or use a sorted list with key function.

**Comment by tomas-teijeiro** [comment]
That's exactly what I tried to show you all this time, that `m[1] in m` returns and displays `False`, sorry for not explaining it more clearly. I believe that a containers library should not give a result such as `m[1] in m == False`, but if you consider that the responsibility belongs to the user, I suggest you to include an explanation in the documentation to prevent the use of partial orders. 

Having said that, I consider that `sortedcontainers` is a great library, and I congratulate you and thank you for your work.

**Comment by grantjenks** [comment]
Thanks for the kind words! I appreciate it. I assumed ``m[1] in m`` was ``True`` until I looked in the Python shell. Sorry I assumed you did too.

I am open to safeguards which would prevent ``m[1] in m == False`` but how would they be implemented? I think you would have to check when the value is added. Maybe something like:

```python
class SaferSortedList(SortedList):
    def add(self, value):
        super(SaferSortedList, self).add(value)
        assert value in self
```

But this would slow things down considerably. It may also be possible to check for ``__eq__`` and ``__lt__`` but those will be defined for all types inheriting from ``object``. I am afraid there's no easy way to check.

Perhaps a comment is warranted in the docs? Where would you have seen that comment and what would it have needed to explain?

**Comment by tomas-teijeiro** [comment]
I think that changing the documentation of the affected methods would be enough. For example, the [SortedList](http://www.grantjenks.com/docs/sortedcontainers/sortedlist.html) documentation says, for the `x in L` operator: `Return True if and only if x is an element in the list.` I would explain how membership is checked, and the assumptions made on the comparison operators. The other methods that should change the documentation are `index()`, `count()`, `remove()` and `discard()`.

**Comment by easying** [comment]
Related:
 
Similarly a `ValueError` might be thrown when the key operator changes on the fly as in the following snippet `l = SortedList(key=lambda x: randint(0,1))`. This can lead to `ValueError` when attempting to `remove()` an element etc.

**Comment by grantjenks** [comment]
Rewrote introduction at 03aed3b. To be deployed in V2 (this month).
