### ISSUE TITLE
pickle support for ValueSortedDict

### ISSUE THREAD

**Issue by Gra55h0pper** [grantjenks/sorted_containers#65]
Pickle works for SortedDict but not for ValueSortedDict. Is this something that would be possible to support?

from sortedcollections import ValueSortedDict, SortedDict

pickle.loads(pickle.dumps(SortedDict({1:2, 3:4})))
--> works

pickle.loads(pickle.dumps(ValueSortedDict({1:2, 3:4})))
--> AttributeError: Can't pickle local object 'ValueSortedDict.__init__.<locals>.key_func'

Thanks much. This is a great module!

**Comment by grantjenks** [comment]
Fixed in version 0.5.3 of the sortedcollections module.

Commit: https://github.com/grantjenks/sortedcollections/commit/c8444b3f6847e1cd73895a7b5e630a9753fa02dc

Run:

    $ pip install --upgrade sortedcollections
