### ISSUE TITLE
Switching from banyan to SortedContainers in pyannote.core

### ISSUE THREAD

**Issue by hbredin** [grantjenks/sorted_containers#66]
Most of the issues raised by the users of my library [`pyannote.core`](http://pyannote.github.io/pyannote-core/) relates to the installation of `banyan`. And, as you know, `banyan` is no longer supported.

Therefore, as you suggested in https://github.com/cpcloud/banyan/issues/1, I plan to switch from `banyan` to `SortedContainers` to store (and search in) a sorted list of (possibly overlapping) intervals (called `Segment` in `pyannote.core` -- http://pyannote.github.io/pyannote-core/reference.html#pyannote.core.Segment). Intervals [a, b] are sorted by increasing a, then increasing b.

However, I am relying on the `updator` functionality of `banyan` that (as far as I understand) is missing in `SortedContainers`. In particular, each node of the underlying tree structure should contain the englobing interval of all intervals in the corresponding subtree. This is useful for efficient implementation of the following features (in addition to other readily available features such as iterating over intervals in sorted order -- see http://pyannote.github.io/pyannote-core/reference.html#pyannote.core.Timeline for the whole API):

- get the englobing intervals of all intervals in the list
- get the list of intervals overlapping a specific value
- given two list of intervals, iterate over pairs of intersecting intervals

These problems are easy when intervals are not overlapping. 
However, they are much more complex when intervals may be overlapping (or worse, englobing) each other.

In practice, I don't really need a generic `updator` functionality. 
A specific `SortedListOfIntervals` class would be enough for me.

My question: where should I start to add this kind of functionality to `SortedContainers`?

**Comment by grantjenks** [comment]
In short, I have not been able to provide interval-tree functionality from SortedContainers and I doubt it is possible with the current design.

But, I do think it's possible to construct an efficient pure-Python implementation of the interval-tree that would suit your needs. I created a pull request with some refactoring in interval_tree.py towards this end: https://github.com/pyannote/pyannote-core/pull/11

You can read about the implementation of SortedContainers at http://www.grantjenks.com/docs/sortedcontainers/implementation.html The design is like that of a B-tree but with only two levels of nodes. As a B-tree, there's already some metadata maintained at the top-level, namely the ``_maxes`` index. You may be able to extend that index with the metadata you need but I could not figure out an efficient way.

If you want to add this functionality to SortedContainers then I would start with ``sortedcontainers.SortedList`` and focus on the ``overlapping`` and ``co_iter`` methods. Those, you will see in my pull request, are least efficient. I have an idea for implementing ``extent`` which would be speedy but I had not time to implement it.

I did some Google searching and found: https://github.com/chaimleib/intervaltree I wonder if it would work for your needs. I am afraid though that it is fairly slow. Do you have a benchmark we could use?

**Comment by hbredin** [comment]
Thanks a lot, @grantjenks, for your feedback and pull request! 

I think `extent` is the critical part. Once it is implemented (and fast), the other two should be quite easy to implement. If you don't mind, can you tell me quickly about your idea for implementing `extent`? I will then try to implement it myself, after carefully reading the implementation details of SortedContainers...

As far as benchmarks are concerned, I do not have one per se.
But `pyannote.core` does have a test suite whose execution time can be measured.
It is obviously not ideal (it uses a small number of intervals) but this is all I have (for now...)

I won't be able to work on that next week but will definitely give it a go after that.
I'll keep you updated!

**Comment by grantjenks** [comment]
Closing this issue. Pull request with changes at https://github.com/pyannote/pyannote-core/pull/11
