### ISSUE TITLE
Document defaultdict Recipe Using __missing__

### ISSUE THREAD

**Issue by grantjenks** [grantjenks/sorted_containers#74]
Reminder: check support for __missing__ method

**Comment by grantjenks** [comment]
Based on the data model at https://docs.python.org/3/reference/datamodel.html#object.__missing__ I think SortedDict already supports __missing__ because it uses the inherited __getitem__ method.

**Comment by aberres** [comment]
Looks good I'd say.  
I "ported" a default dict from our code base from `OrderedDict` to `SortedDict` and found nothing obviously wrong.

```python
class SortedOrderedDefaultDict(SortedDict):
    def __init__(self, default_factory=None, *args, **kwargs):
        if not (default_factory is None
                or isinstance(default_factory, Callable)):
            raise TypeError('First argument must be callable or None')
        super().__init__(*args, **kwargs)
        self.default_factory = default_factory

    def __missing__(self, key):
        if self.default_factory is None:
            raise KeyError(key, )
        self[key] = value = self.default_factory()
        return value```

**Comment by grantjenks** [comment]
Rewrote introduction at 03aed3b. To be deployed in V2 (this month).
