### ISSUE TITLE
SortedDict.next_item(key), SortedDict.prev_item(key)

### ISSUE THREAD

**Issue by oscardssmith** [grantjenks/sorted_containers#75]
I am currently using a SortedDict in a problem where I only want to add a new (key, value), if the value is greater than the value for the next biggest element. To do this I currently use the following code.
    key, val = 10, 4
    index = d.bisect(key) - 1
    if val > d.values()[index]:
                d[key] = val
    While this works, it is pretty inefficient, because it forces lots of index traversals. If there was a function that returned the previous item in the dictionary, I believe this code would be around twice as fast.

**Comment by grantjenks** [comment]
I think this will do it:

```python
from bisect import bisect_right

class SortedDictWithCustomInsert(SortedDict):
    def custom_insert(self, key, value):
        _list = self._list
        _maxes = _list._maxes

        if not _maxes:  # Empty dictionary case.
            self[key] = value
            return

        # Find the sublist.

        pos = bisect_right(_maxes, key)

        if pos == len(_maxes):
            pos -= 1

        sublist = _lists[pos]

        # Find the index.

        index = bisect_right(sublist, key)

        # Lookup the previous index.

        if index:
            index -= 1
        else:
            if pos:
                sublist = _lists[pos - 1]
                index = len(sublist) - 1
            else:
                # We're at index 0. What to do here?
                return

        if value > self[sublist[index]]:
            self[key] = value
```

I haven't tested that code though. Maybe you could share a test case. This will avoid the positional index entirely.

**Comment by oscardssmith** [comment]
it gives me `File "test.py", line 177, in custom_insert
    sublist = _lists[pos]
NameError: name '_lists' is not defined` should `_list = self._list` be `_lists = self._lists` instead?

**Comment by oscardssmith** [comment]
Also, thanks so much for the quick response

**Comment by grantjenks** [comment]
I edited it to fix the NameError

**Comment by oscardssmith** [comment]
Thanks so much

**Comment by grantjenks** [comment]
I thought about adding the API but I don't really like it. There's a big speedup to be had by avoiding the positional index but it seems specific to this case. If other issues request similar functionality in the future, maybe we'll do something then.

**Comment by oscardssmith** [comment]
Also, just for the record, I ended up going with a faster solution of making my own `StrictSortedDict` (keys and values must be ascending) using a custom `SortedList` The big advantage of this approach for me was to allow bisect_right with a left index I've attached my setitem code to give an idea

    def __setitem__(self, key, value):
        keys = self._keys
        values = self._values
        if not keys:
            keys.add(key)
            values.add(value)
            return
        
        l_bound = bisect_left(keys, key)
        
        if l_bound > 0 and values[l_bound-1] >= value:
            return
            
        r_bound = bisect_right(values, value, l_bound)
        if r_bound > l_bound:
            del keys[l_bound+1:r_bound]
            del values[l_bound+1:r_bound]
            keys[l_bound] = key
            values[l_bound] = value
        else:
            keys.insert(l_bound, key)
            values.insert(l_bound, value)
