### ISSUE TITLE
Add a big fat warning in doc about changing "in-place" order, breaking a lot

### ISSUE THREAD

**Issue by potens1** [grantjenks/sorted_containers#76]
Hi,

First of all, thank you for your nice lib !

I've come across some little problem yesterday, and, now I understand it's working the way it should but I had a hard time to find it. Maybe some words should be put in doc about it. Let me explain the problem:
```python
@total_ordering
class Foo(object):
     def __init__(self, val):
        self.a = val
     def __lt__(self, other):
        return self.a < other.a
     def __eq__(self, other):
        return self.a == other.a

a, b, c = Foo(1), Foo(2), Foo(3)
mylist = SortedList([a, b, c])

b in mylist
True
c in mylist
True
b.a = 7
b in mylist
False
c in mylist
False
c == mylist[2]
True
b == mylist[1]
True
```
So sorting is not kept, *and* `in` is broken. I've seen in #39 how it should be done, but even, I think a bit of doc could be added about it, since, in the intro this is written: "A SortedList may never contain its elements out of order." since I'm not a native English speaker, I understand in this sentence "Either this will raise an Error, either the SortedList is kept ordered, whatever what you do" (I know, this is magic).

So a "**Warning:** Sorted[List/Dict/Set...] are not in charge of keeping elements ordered and if order is broken, most of the methods and algorithm will be broken" could be useful.

**Comment by grantjenks** [comment]
I agree, it's worth adding something to the docs.

The dict data type has a similar problem in Python:

```python
>>> class Test:
...     def __init__(self, value):
...         self.value = value
...     def __eq__(self, other):
...         return self.value == other.value
...     def __hash__(self):
...         return hash(self.value)
... 
>>> test = Test(0)
>>> d = {test: 'something'}
>>> test in d
True
>>> test.value = 5
>>> test in d
False
>>> test in list(d)
True
```

**Comment by amras0000** [comment]
I would add that SortedSet in particular can contain duplicate elements when this occurs.

```python
class T:
     def __init__(self, val):
        self.val = val

s = SortedSet(key=lambda x: x.val)
a = T(0)

s.add(a)
a.val = 1
s.discard(a)  # here a is removed from s._set but not from s._list
s.add(a)      # now a is re-added to _set and a copy of a is added to _list
a.val = 2
s.discard(a)  # we would now expect s to contain no a's, but in fact it contains 2 copies of the object.
```

**Comment by grantjenks** [comment]
Rewrote introduction at 03aed3b. To be deployed in V2 (this month).
