### ISSUE TITLE
SortedListWithKey can't be pickled if key is specified

### ISSUE THREAD

**Issue by Nitrooo** [grantjenks/sorted_containers#78]
pickle.loads(pickle.dumps(SortedListWithKey([1, 2]))) # all fine
pickle.loads(pickle.dumps(SortedListWithKey([1, 2], key=lambda x: x))) # error

_pickle.PicklingError: Can't pickle <function <lambda> at 0x02BDDBB8>: attribute lookup <lambda> on __main__ failed

It seems like Python can't pickle lambda functions. Should I use a library like dill to pickle SortedListWithKey or is there a workaround for that error?

**Comment by grantjenks** [comment]
That's right, pickle doesn't work on lambda functions. You could use `dill` but simpler is to simply use a named function:

```python
def negate(x):
    return -x

pickle.loads(pickle.dumps(SortedListWithKey([1, 2], key=negate)))  # Works fine.
```

**Comment by Nitrooo** [comment]
Thanks for you answer.
It's worth noting that a named function would work only if the function is defined in the namespace at load time and it's not guaranteed that it will be the same function used at dump time.

**Comment by grantjenks** [comment]
Yes, all true although I do think you get the same function back and it could be defined in a different module. For example, using pickle with operator.neg as the key would work fine and load back the reference to operator.neg.

Dill is still superior in several ways and SortedContainers is compatible with each
