### ISSUE TITLE
SortedList.reverse() corrupts sorted list

### ISSUE THREAD

**Issue by sedwards2** [grantjenks/sorted_containers#79]
If I have a SortedList() and perform an in-place reverse, I get a ValueError. This seems like a bug.

Traceback (most recent call last):
  File "/home/sedwards/study/sortedcontainers_reverse_in_place_error.txt.py", line 6, in <module>
    sl.reverse()
  File "/usr/lib/python3.5/_collections_abc.py", line 915, in reverse
    self[i], self[n-i-1] = self[n-i-1], self[i]
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sortedlist.py", line 790, in __setitem__
    _check_order(index, value)
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sortedlist.py", line 666, in _check_order
    raise ValueError(msg)
ValueError: 2 not in sort order at index 1

Reproduction:

from sortedcontainers import SortedList

sl = SortedList()
sl.add(2)
sl.add(4)
sl.reverse()
print(sl)

**Comment by grantjenks** [comment]
Yup. You can't reverse a sorted list. That would violate the sort order. Sorted list elements are ordered in ascending order. The reverse() method is an unfortunate result of inheriting from MutableSequence in the collections module.

So a couple questions:

1. What docs are missing to explain that a sorted list cannot be reversed?
2. What exception should be raised when calling reverse()?

**Comment by sedwards2** [comment]
Ok, this makes sense now that I think about it.

1. Perhaps add an explanation to: http://www.grantjenks.com/docs/sortedcontainers/introduction.html#sortedlist for reverse()

2. https://docs.python.org/3/library/exceptions.html#NotImplementedError seems reasonable

Thanks

**Comment by grantjenks** [comment]
Fixed and deployed at v1.5.9
