### ISSUE TITLE
Adding cmp_func to SortedList.remove?

### ISSUE THREAD

**Issue by dsuch** [grantjenks/sorted_containers#81]
Hello,

I'm wondering about one thing - I'm using SortedList with instances of classes that define a custom ```__cmp__``` method.

They are messages of a message queue sorted by user-defined criteria the most basic of which is msg.priority, e.g. there can be a list of messages, each completely unrelated and ```__cmp__``` dictates that their .priority attributes are what drives their order in a SortedList.

This all works fine in the sense that the messages are sorted as told to except that when I remove messages from that container, I can see in .remove method that ultimately there is this check ```if _lists[pos][idx] == val:``` which I'm sure is fine for integers or strings but not really for classes with ``__cmp__``.

Consider the snippet below using sortedcontainers 1.5.9 - I realize that this is how Python's own lists work too but I just wonder if with sortedcontainers there could not be a cmp_func argument added to .remove (likely to .discard too) in order to let one customize the behaviour, i.e. I find it great that the container is sorted and I take advantage of it with my own ```__cmp__``` but this actually interferes with the ability to remove items later on.

```python
from sortedcontainers import SortedList

class Msg(object):
    def __init__(self, priority, data):
        self.priority = priority
        self.data = data

    def __cmp__(self, other):
        return cmp(self.priority, other.priority)

sorted_list = SortedList()

msg1 = Msg(5, 'foo')
msg2 = Msg(5, 'bar')
msg3 = Msg(5, 'baz')

sorted_list.add(msg1)
sorted_list.add(msg2)
sorted_list.add(msg3)

sorted_list.remove(msg3)

# This prints 'bar' instead of 'foo' because msg1 was actually removed rather than msg3
print(sorted_list[0].data)

# This prints 'baz' instead of 'bar'
print(sorted_list[1].data)
```

Regards.

**Comment by dsuch** [comment]
Just in case it helps anyone - I dealt with it by subclassing SortedList and introducing an application-specific method to remove elements from a sorted list of messages:

```python
def remove_pubsub_msg(self, msg):
    """ Removes a pubsub message from a SortedList instance - we cannot use the regular
   .remove method because it may triggger __cmp__.
    """
    pos = bisect_left(self._maxes, msg)

    if pos == len(self._maxes):
        raise ValueError('{0!r} not in list'.format(val))

    for _list_idx, _list_msg in enumerate(self._lists[pos]):
        if msg.pub_msg_id == _list_msg.pub_msg_id:
            idx = _list_idx
            break
    else:
        raise ValueError('{0!r} not in list'.format(msg))

    self._delete(pos, idx)
```

**Comment by grantjenks** [comment]
SortedList is behaving as expected here. Your `__cmp__` method defines equality only in terms of priority. So as far as Python knows, `Msg(5, 'foo') == Msg(5, 'bar')` is True. If you want ordering and equality to work then change your `Msg` object like so:

```python
class Msg(object):
    def __init__(self, priority, data):
        self.priority = priority
        self.data = data

    def __cmp__(self, other):
        return cmp((self.priority, self.data), (other.priority, other.data))
```

That'll order messages by priority and break ties by data. It'll also define equality in terms of both. Does that make sense?

It's also a little odd to see the old comparison methods. In Python 3, you'll need the rich comparison operators: `__eq__`, `__lt__`, etc.

**Comment by dsuch** [comment]
I see, thanks for the update @grantjenks !
