### ISSUE TITLE
SortedSet index/remove/discard do not follow ordering function

### ISSUE THREAD

**Issue by mgdelmonte** [grantjenks/sorted_containers#83]
As of v1.5.9, the `index`, `remove`, and `discard` functions in a SortedSet do not obey the python data model, which allows redefinition of `__hash__` and `__eq__` (and `__ne__` for completeness).  Other SortedSet functions do appear to work properly (though I haven't tested them all).

Here's a sample to reproduce the problem.  The `Item` class is defined so that it's keyed on only the `id` field; `name` is not part of the hash.  A clue: `discard` and `remove` work, but only if ordering *including the name* would result in the item being found at the expected location.  (If the set is ordered based on any other function than tuple value, these functions fail under all conditions.)

```
import collections
import sortedcontainers
class Item(collections.namedtuple('Item', ['id', 'name'])):
    def __hash__(self):
        return self.id
    def __eq__(self, other):
        return self.id == other.id
assert Item(1, 'a') == Item(1, 'b') == Item(1, '')
s = sortedcontainers.SortedSet()
s.add(Item(1,'a'))
s.remove(Item(1, 'b'))  # ValueError: Item(id=1, name='b') not in list
s.discard(Item(1, 'b')) # fails to discard
s.index(Item(1, 'b'))  # ValueError: Item(id=1, name='b') not in list
# using empty string as name has different behavior
s.clear()
s.add(Item(1, 'a'))
s.index(Item(1, '')) # same ValueError: Item(id=1, name='') is not in list
s.discard(Item(1, ''))  # works!
s.clear()
s.add(Item(1, 'a'))
s.remove(Item(1, ''))  # works!
```

The underlying problem appears to be in the underlying SortedList, which doesn't respect the hash/equality functions.

**Comment by grantjenks** [comment]
In your example, item instances are both “==“
and “<“ or “>” than each other. That violates the total ordering requirements of sorted containers. If you define dunder lt and the other rich comparison operators based on id then it will work as you expect.

**Comment by mgdelmonte** [comment]
True.  But then it fails if you define the SortedSet with a sorting key:

```
import sortedcontainers
class Item(collections.namedtuple('Item', ['id', 'name'])):
    def __hash__(self):
        return self.id
    def __eq__(self, other):
        return self.id == other.id
    def __ne__(self, other):
        return self.id != other.id
    def __lt__(self, other):
        return self.id < other.id
    def __gt__(self, other):
        return self.id > other.id
assert Item(1, 'a') == Item(1, 'b') == Item(1, '')
s = sortedcontainers.SortedSet(key=lambda x:x.name)
s.add(Item(1, 'a'))
s.add(Item(2, 'b'))
s.add(Item(3, 'a'))
# so far so good ^
s.remove(Item(1, 'b'))  # ValueError: Item(id=1, name='b') not in list
```

After the failure, s._set has len=2 and s._list has len=3.

**Comment by grantjenks** [comment]
Is there a typo? (1, ‘b’) doesn’t appear in the list to me.

**Comment by grantjenks** [comment]
Oh wait, you just mean that the sorted set is corrupted at that point? Hmm, I could believe that. The set removal succeeds but the list removal fails.

I’m not sure that’s a bug. I think the key property is a bit like the hash property, equal objects must have equal keys but equal keys don’t necessarily mean equal objects. You’ve violated that property in your items.

It’s certainly clear to me that a section of the docs dedicated to these properties is well worth it.

**Comment by mgdelmonte** [comment]
No typo.  `assert Item(1,'b') == Item(1,'a')` is correct.  It's only the id part of the Item that matters.

I'd say it's a bug, if the point of the SortedSet is to maintain a set (i.e., all items are unique) sorted in a particular order (as defined by the key function).  It does that well, and the SortedSet works great for that purpose -- so long as you don't use the `remove`, `discard`, or `index` functions.  Every other set operation, plus sorted inserts, all work perfectly.  The `pop` function also works -- because you give it an index, instead of having it look it up in the `_list`.  It's just the lookup in the `_list` that's done wrong.

**Comment by grantjenks** [comment]
I thought about it more. It's not a bug. The assumption is equal objects have equal keys. Both [sortedcollection](http://code.activestate.com/recipes/577197-sortedcollection/) and [blist](https://pypi.python.org/pypi/blist) make the same assumption and I think it's a reasonable one.

It's possible to build what you want but it's not what sorted containers currently provides.

I'll open a different issue as a reminder to document the "key" requirements.
