### ISSUE TITLE
SortedSet does not support __setitem__ as docs claim

### ISSUE THREAD

**Issue by tobiashagge** [grantjenks/sorted_containers#85]
SortedSet documentation claims that S[i] = v should work (and support slice notation) but I get an AttributeError for __setitem__ when I try it. Maybe I'm missing something but I can't find an implementation in the code or coverage of the behavior in the unit tests; I suspect it's a documentation error.

**Comment by grantjenks** [comment]
It is a documentation error. I removed that functionality and forgot the docs.

Were you needing that functionality or just surprised by the docs?

**Comment by grantjenks** [comment]
Documentation fixed in V2, to be deployed in May, 2018.
